# Generated by Django 4.0.4 on 2022-08-08 17:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learning_environment', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='feedback',
        ),
        migrations.AddField(
            model_name='taskanswer',
            name='feedback',
            field=models.TextField(null=True),
        ),
    ]
