# Generated by Django 4.0.4 on 2022-08-28 19:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('learning_environment', '0002_remove_task_feedback_taskanswer_feedback'),
    ]

    operations = [
        migrations.CreateModel(
            name='LessonOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.IntegerField()),
                ('lesson', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='learning_environment.lesson')),
            ],
        ),
        migrations.RemoveField(
            model_name='learner_lesson',
            name='order',
        ),
        migrations.AddField(
            model_name='module',
            name='name',
            field=models.CharField(default='Module', max_length=255),
            preserve_default=False,
        ),
        migrations.RemoveField(
            model_name='module',
            name='lesson',
        ),
        migrations.AddField(
            model_name='module',
            name='lesson',
            field=models.ManyToManyField(through='learning_environment.LessonOrder', to='learning_environment.lesson'),
        ),
        migrations.AlterField(
            model_name='module',
            name='level',
            field=models.CharField(choices=[('1', 'Textbook'), ('2', 'General texts'), ('3', 'Spezialized Texts')], max_length=100, unique=True),
        ),
        migrations.AddField(
            model_name='lessonorder',
            name='module',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='learning_environment.module'),
        ),
    ]
