# Generated by Django 4.1.1 on 2022-10-04 20:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("learning_environment", "0003_profile"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="profile",
            name="bio",
        ),
        migrations.RemoveField(
            model_name="profile",
            name="birth_date",
        ),
        migrations.RemoveField(
            model_name="profile",
            name="location",
        ),
        migrations.AddField(
            model_name="profile",
            name="level",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="profile",
            name="nickname",
            field=models.CharField(default="Llama", max_length=64),
        ),
    ]
