# Generated by Django 4.0.4 on 2022-08-31 14:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('learning_environment', '0003_lessonorder_remove_learner_lesson_order_module_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='learner_task',
            name='answer',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='learning_environment.answer'),
        ),
        migrations.AlterField(
            model_name='taskanswer',
            name='value',
            field=models.IntegerField(null=True),
        ),
    ]
