# Generated by Django 4.1.1 on 2022-10-12 07:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "learning_environment",
            "0004_remove_profile_bio_remove_profile_birth_date_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="task",
            name="interaction",
            field=models.CharField(max_length=10),
        ),
    ]
