# Generated by Django 4.1.4 on 2022-12-09 12:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learning_environment', '0006_remove_profile_level_lesson_series_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='gamification_active',
            field=models.IntegerField(default=0),
        ),
    ]
