# Generated by Django 4.1.3 on 2022-12-05 20:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("learning_environment", "0007_lesson_start_lesson_wrapup"),
    ]

    operations = [
        migrations.RemoveField(model_name="lesson", name="start",),
        migrations.RemoveField(model_name="lesson", name="wrapup",),
    ]
