# Generated by Django 4.2.2 on 2023-06-22 20:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learning_environment', '0007_lesson_start_lesson_wrapup'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='gamification_active',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='profile',
            name='gamification_level',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='profile',
            name='last_active',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='streak_counter',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='profile',
            name='total_XP',
            field=models.IntegerField(default=0),
        ),
    ]
