# Generated by Django 4.1.1 on 2022-10-26 11:22

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("learning_environment", "0007_lesson_start_lesson_wrapup"),
    ]

    operations = [
        migrations.AddField(
            model_name="lesson",
            name="tutor_mode",
            field=models.CharField(max_length=10, null=True),
        ),
    ]