# Generated by Django 4.2 on 2023-07-05 13:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learning_environment', '0008_streak_gamificationuser'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lesson',
            name='series',
            field=models.CharField(default='Academic English', max_length=255),
        ),
    ]
