# Generated by Django 4.1.4 on 2022-12-13 20:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learning_environment', '0008_profile_gamification_level_profile_total_xp_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='streak_counter',
            field=models.IntegerField(default=1),
        ),
    ]
