# Generated by Django 4.1.4 on 2022-12-13 20:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('learning_environment', '0007_lesson_start_lesson_wrapup'),
        ('learning_environment', '0009_profile_streak_counter'),
    ]

    operations = [
    ]
