# Generated by Django 4.1.4 on 2022-12-15 12:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('learning_environment', '0011_profile_last_day'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='last_day',
            new_name='last_active',
        ),
    ]
